
package web;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Consulta", targetNamespace = "http://web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Consulta {


    /**
     * 
     * @param cadenaXML
     * @param identificador
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registroFormMiscelaneo", targetNamespace = "http://web/", className = "web.RegistroFormMiscelaneo")
    @ResponseWrapper(localName = "registroFormMiscelaneoResponse", targetNamespace = "http://web/", className = "web.RegistroFormMiscelaneoResponse")
    public List<String> registroFormMiscelaneo(
        @WebParam(name = "identificador", targetNamespace = "")
        String identificador,
        @WebParam(name = "cadenaXML", targetNamespace = "")
        List<String> cadenaXML)
        throws Exception_Exception
    ;

}
