package web;

import java.util.Iterator;
import java.util.List;

import javax.crypto.Cipher;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 11g Release 2 11.1.2.0.0.6017

public class wsfmismodbnkClient
{
  public static void main(String [] args)
  {
    
    
    Wsfmismodbnk wsfmismodbnk = new Wsfmismodbnk();
    Consulta consulta = wsfmismodbnk.getWsfmismodbnk();
      RegistroFormMiscelaneo resp=new RegistroFormMiscelaneo();
      List<String> list = resp.getCadenaXML();
      resp.setPListStringXML(list);
        
      list.add("N95W8kDSb1xlXksFa3oGhEDSqlfMAg0q2lfJthMis5mmSOLGjyoCEJZX4xrVXhgH5YDg7DDXaV2HAiZPhQyw1Ah+9JpXeJB214WkdFpGXKe9oAO293Nz5xHmZ7Na8OH/ErLAJr6LELSlRJziTuJaakuCQzjbU3vRulW82Qgf+Qg3HB89pmeYCVbvY2EjRnhABBNRQ5MWuCfIEg128R2rLj/8fymgOhDrLoWUOYMorMUCvdMqXtgoGrlviSHmXTWk3pCQYflhZwGlJMGnKoQNQ84iASnOcGoKRMrHFuV1VJz5mJg37YM8wOu/3pRS4JuahjXsXxEJ5U2wqDWUp67iOQ==");
      list.add("TP7L3tFdlmB/B6OfXp6L9fUhV0IAXwIOK0vREQWMPWOGjWl4/ZuiweplIbq+0Of+B7wo0zN2sOl61StpAk+pezT5ejb02fZYOk3i65EDkwJ9mcaY74ZireXmXIU+W4FhECBJx9FFPtRSOOXFQ/l6cRM8Cl6XHqgo3SwlKBlUOhUH4lDG9Hx/gIQUaSW+nWZZ8NtwgqmpWcJx3wkvwyPsg+PE57VLYcfwm34+ASWwpfclJySPgMN9MqyflqW+CUSazRHyYogsfcQBuf3QfQCIL+QjrOuVvx+LyS8vyF55LeuNvV/MWcnWZha52UoxXxqUG1g6H7QBWJ7o79xyfc19fA==");
      list.add("BP+adovZ+N9fk6/Jhikku9bvFoGAqu148Xvfu+p1fdVRqGh65qjRQusLCjyYlv8W90+WCzECUrrl2GjYi1IUyJZXvByY8bio2WRCBHaQH8+2UWME3Jev8WkT+8oHi1ywPYDNNeKcx2uzshpyKC6C8ninUw5fRYAkGNUtpbiiRnPDPN8CIS5YTmFD30LvRdERI+650LiJculxO/MLQiCBJLvOtvb/7MQaNj+QIBmK0z47tKnNZpjklQNQOsLfnHL098PK7HrLZVA91r6LmNYC1+/Iij9m43xEnSwJPewCXNt+wPoyOPFyueX6ovH+cQcYKZDm7dhNHLlDly7YFZOzBA==");
      list.add("PwHjeDTcr7DyY98qWrJn05Bnr580mvCyOZ2sGKFRNnJeCBYA3m1r2iQK7DONZf92evh2jEAjoENVrweWhzBIPipLpLi2NOLH0RpYTtfp/Cn0KQ8Mu2jjy3l2sOBbk359QzEG/lZb1s+nKarril9V4nshq1p/WIUXD8naOEsZApygXnJ3TOYWDGNjKflZScX0UYbgox54S/67Lj94vrmgmSdUsQjqdINXh1ErkE8okXgIx/gSHbqgyD13WF+TcUkwYVvtxtVOuujNlcpJkeJdBX2SHkhvGJAqk2JNi3nvMTOdUKaUGEZClDf1mf6Jyn/Py2F5qcV9DT/nfZZa/QYhNA==");

        //consulta.registroFormMiscelaneo("sfdfsdf", list);
    // Add your code to call the desired methods.
        try {
            List<String> list2 = resp.getCadenaXML();
            list2=consulta.registroFormMiscelaneo("fM3n7VcaBSQfZYk2auojmEp2teyim8Fv", list);
           System.out.println("es:"+ list2.get(0));
         //   String cadena=decryptList(list);
          //  System.out.println(cadena);
            
        } catch (Exception_Exception e) {
            System.out.println("es:"+ e.getMessage());
        }
    }
  

  /*
    private static RegistroFormMiscelaneoResponse solicitudForm(RegistroFormMiscelaneo solicitudEncrypt) {
           Wsfmismodbnk service = new Wsfmismodbnk();
         //  org.openuri.ServicioANBSoap port = service.getServicioANBSoap();
           return port.regVehiculoFRM(solicitudEncrypt);
       }*/
}
